import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

type PackageJson = {
  name: string;
  description?: string;
  homepage?: string;
  llms?: string;
  llmsFull?: string;
  skills?: string;
  agents?: { skills: Array<{ name: string; path: string }> };
  repository?: { url?: string; directory?: string };
};

const packageDir = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
const repoRoot = path.join(packageDir, "../..");
const packageJson = JSON.parse(
  readFileSync(path.join(packageDir, "package.json"), "utf8"),
) as PackageJson;

function parseGitHubRepo(url: string | undefined) {
  const match = url?.match(/github\.com[/:]([^/]+)\/([^/.]+)/);
  return match ? { owner: match[1], name: match[2].replace(/\.git$/, "") } : null;
}

const packageSlug = path.basename(packageDir);
const npmName = packageJson.name;
const npmSlug = npmName.replace("/", "%2f");
const repo = parseGitHubRepo(packageJson.repository?.url);
const siteBase = `https://${repo!.owner}.github.io/${repo!.name}`;
const docsUrl = `${siteBase}/docs`;
const repoUrl = packageJson.repository?.url?.replace(/^git\+/, "").replace(/\.git$/, "");
const repoTreeUrl =
  repoUrl && packageJson.repository?.directory
    ? `${repoUrl}/tree/main/${packageJson.repository.directory}`
    : repoUrl;
const skillGitUrl =
  repoUrl && packageJson.repository?.directory
    ? `${repoUrl}/tree/main/${packageJson.repository.directory}/skills/${packageSlug}`
    : undefined;
const ciWorkflow = "on-push-main.yml";
const ciBadgeUrl = `https://img.shields.io/github/actions/workflow/status/${repo!.owner}/${repo!.name}/${ciWorkflow}?branch=main&label=main`;
const ciLinkUrl = `https://github.com/${repo!.owner}/${repo!.name}/actions?query=branch%3Amain`;

const badges = [
  `[![npm version](https://img.shields.io/npm/v/${npmSlug})](https://www.npmjs.com/package/${npmSlug})`,
  `[![npm downloads](https://img.shields.io/npm/dm/${npmSlug})](https://www.npmjs.com/package/${npmSlug})`,
  `[![main](${ciBadgeUrl})](${ciLinkUrl})`,
  `[![skills.sh](https://skills.sh/b/${repo!.owner}/${repo!.name})](https://skills.sh/${repo!.owner}/${repo!.name})`,
].join("\n");

const readme = `<!-- Generated by packages/seokit/scripts/readme-gen.ts -->

# ${npmName}

${badges}

${packageJson.description}

Wire them with \`extendSeokitExpect\` and assert page SEO contracts in Playwright specs. That is the whole public product.

## Install

\`\`\`bash
npm install ${npmName} @playwright/test
\`\`\`

Formerly published as \`@sargonpiraev/seodit\` — same matcher API, new package name:

\`\`\`bash
npm uninstall @sargonpiraev/seodit
npm install ${npmName} @playwright/test
\`\`\`

## Quick start

\`\`\`typescript
import { expect as baseExpect, test } from "@playwright/test";
import { extendSeokitExpect } from "${npmName}";

const expect = extendSeokitExpect(baseExpect);

test("/en", async ({ page }) => {
  await page.goto("/en");
  await expect(page).toHaveMetadata({
    lang: "en",
    title: /.+/,
    alternates: { canonical: "https://example.com/en" },
  });
  await expect(page).toHaveJsonLd([{ "@type": "Organization" }]);
});
\`\`\`

## Skill (optional)

For Cursor and other coding agents. [Skill docs](${docsUrl}/skill).

**skills.sh**

\`\`\`bash
npx skills add ${skillGitUrl ?? `${repo!.owner}/${repo!.name}`} -a cursor -y
\`\`\`

**skills-npm** (version-locked)

\`\`\`bash
npm i -D skills-npm
npx skills-npm setup
npm install ${npmName}
\`\`\`

## Documentation

- [Docs](${docsUrl})
- [llms.txt](${siteBase}/llms.txt)
- [llms-full.txt](${siteBase}/llms-full.txt)
${repoTreeUrl ? `- [Source](${repoTreeUrl})` : ""}
- [npm](https://www.npmjs.com/package/${npmSlug})
- [Example app](${repoUrl}/tree/main/apps/example)
`;

writeFileSync(path.join(repoRoot, "README.md"), readme);
writeFileSync(path.join(packageDir, "README.md"), readme);

const skillDir = path.join(packageDir, "skills", packageSlug);
mkdirSync(skillDir, { recursive: true });

const skill = `---
name: ${packageSlug}
description: Add two Playwright SEO matchers via extendSeokitExpect — toHaveMetadata and toHaveJsonLd. Use for *.seokit.spec.ts, canonical, hreflang, robots meta, or JSON-LD checks.
---

<!-- Generated by packages/seokit/scripts/readme-gen.ts -->

# ${packageSlug}

${packageJson.description}

## When to use

- Asserting page metadata (title, description, canonical, hreflang, robots)
- Asserting JSON-LD structured data in Playwright specs

## Instructions

1. Install: \`npm install ${npmName} @playwright/test\`
2. Read [Overview](${docsUrl}) then [Getting started](${docsUrl}/getting-started)
3. Shared \`src/test/seokit.ts\` with \`extendSeokitExpect\`
4. Assert with \`toHaveMetadata\` and \`toHaveJsonLd\`
5. Reference: [Matchers](${docsUrl}/matchers)
6. For HTTP status/headers use Playwright (\`response?.ok()\`, \`response?.status()\`)
7. Import \`test\`/\`expect\` only from the local seokit test module
`;

writeFileSync(path.join(skillDir, "SKILL.md"), skill);

packageJson.homepage = docsUrl;
packageJson.llms = `${siteBase}/llms.txt`;
packageJson.llmsFull = `${siteBase}/llms-full.txt`;
packageJson.skills = skillGitUrl;
packageJson.agents = {
  skills: [{ name: packageSlug, path: `./skills/${packageSlug}` }],
};
writeFileSync(
  path.join(packageDir, "package.json"),
  `${JSON.stringify(packageJson, null, 2)}\n`,
);
