name: on-push-main

on:
  push:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: on-push-main-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: sargonpiraev/ci/.github/workflows/on-push-main-seokit.yml@main
    secrets: inherit
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
      pages: write
